sudo: required

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y wget autoconf automake gcc subversion make pkg-config

services:
  - docker

language: c

compiler: gcc

branches:
   only:
     - master
     
before_script:  
  - "mkdir ~/zabbix30"
  - "cd ~/zabbix30"
  - "svn co svn://svn.zabbix.com/branches/3.0 ."
  - "./bootstrap.sh"
  - "./configure --enable-agent"  
  - "mkdir src/modules/zabbix_module_stress"
script:  
  - "cd src/modules/zabbix_module_stress"  
  - "cp /home/travis/build/monitoringartist/zabbix-server-stress-test/src/modules/zabbix_module_stress/* ."
  - "make"
  - "cd /home/travis/build/monitoringartist/zabbix-server-stress-test/"
  - "bash ./artifacts/deploy.sh"

env:
  global:
  - ENCRYPTION_LABEL: "469b4b5a68a6"
  - COMMIT_AUTHOR_EMAIL: "jan.garaj@gmail.com"
